main:
#	cc -o client client.c # -lsocket
#	cc -o server server.c # -lsocket
	gcc server.c -o server -lsocket
	gcc client1.c -o client1 -lsocket
	gcc client2.c -o client2 -lsocket



clean:
	rm -f client
	rm -f server